export const Latest_Tenfo = [
  {
    id: 1,
    name: "Tender Notice to Purchase Physics Lab Instrument",
    label: "true",
    Link: "",
  },
];
export const Old_Tenfo = [
  {
    id: 1,
    name: "Limited Tender Notice for Miscellaneous Repair Work in Principal Bungalow",
    label: "false",
    Link: "",
  },
  {
    id: 2,
    name: "Notice for Inviting Quotation For Manjari2020",
    label: "false",
    Link: "",
  },
  {
    id: 3,
    name: "Quotation Notice For Miss DRC Event 2019",
    label: "false",
    Link: "",
  },
  {
    id: 4,
    name: "Sealed Quotations are Invited for providing ERP Software",
    label: "false",
    Link: "",
  },
  {
    id: 5,
    name: "Sealed Quotations are Invited for Construction of Canteen Roof",
    label: "false",
    Link: "",
  },
  {
    id: 6,
    name: "Notice Inviting Quoation for Event in DRC",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Sealed Quotations are Invited For Purchase Of Vaccum Pump in Chemistry Deptt.",
    label: "false",
    Link: "",
  },
  {
    id: 8,
    name: "Sealed Quotations are Invited For Purchase Of Physics Lab Instruments",
    label: "false",
    Link: "",
  },
  {
    id: 9,
    name: "Important Notice For Tender For Non-Destructive Testing Of College Block Western Wing & Library",
    label: "false",
    Link: "",
  },
  {
    id: 10,
    name: "Tender For Non-Destructive Testing Of College Block Western Wing & Library",
    label: "false",
    Link: "",
  },
  {
    id: 11,
    name: "Tender Date Extension Notice For Supply, Installation & Commissioning Of Passengers(8) Lift",
    label: "false",
    Link: "",
  },
  {
    id: 12,
    name: "OPEN TENDER FOR SUPPLY, INSTALLATION & COMMISSIONING OF PASSENGERS(8) LIFT",
    label: "false",
    Link: "",
  },
  {
    id: 13,
    name: "Quotations For Binding Books and Periodical 2018-19",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Quotations Invited For Instruments Under Research Work in Zoology Department",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Daulat Ram College Hostel Notice For Various Work",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Quotation For Printing and Supply of Students Register",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender Notice For White washing work at the Daulat Ram College Hostel",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender Notice For Photocopying & Students Facility Centre",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender Notice For Printing Of College Prospectus 2018-19",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender Notice For Plumbing Service",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender Notice For Manjari-2018",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender Notice For Disposing of Scrap",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender Notice For Manjari-2018",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Quotations Invited For Printing College Magzine 2017-18",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Limited Tender Notice For Making Cabin",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Notice for Quotation for Binding Books 2017-18",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for Supply,Installation & Commissioning of Passengers Lift",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for Outsourcing(Security Staff,Nurse and Housekeeping Staff)",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Quotation For Physics Laboratory Instruments",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for Laundry Service in DRC Hostel",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for Printing and Supply of Student Attendance System",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for Communication Lab Instruments",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for Laundry Service in DRC Hostel",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Limited Tender Notice for Temporary Shed on Terrace",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Sealed Quotations are Invited for Printing College Prospectus 2017",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for WaterProofing and Roof Ceiling repair Work",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Manjari 2017 Tender",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Repair Work of Front Verandah",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Laundry Tender",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for College Whitewashing/Painting",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Revised Canteen Tender for Daulat Ram College",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for Roof Ceiling Repair Work",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Quotation for Binding Library Books",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for College Hostel Mess",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender Notice for Printing of College Hostel Prospectus",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender Notice Under Zebrafish Innovation Project",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender for Waterproofing Treatment",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Quotation for Prospectus Printing-2016",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Quotation for Equipments for Chemistry Department",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender Notice Under Zebrafish Innovation Project",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Limited Tender Notice for Waterproofing work",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Renovation Works For Drinking Water Facility & Toilet Blocks",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Financial Bid",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Technical Bid",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Tender For Construction of Sheds",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Sealed quotation are invited for printing of Students Identity Cards for Academic Year 2015-16",
    label: "false",
    Link: "",
  },
  {
    id: 7,
    name: "Quotation for i cards non-teaching",
    label: "false",
    Link: "",
  },
];
