import React from 'react'
import Departments from "../../../../Components/Sidebar/Departments";
import Commercebanner from "../Commerce/Commercebanner.jsx";
import Commerce from "../../../../Components/DepartSIde/Commerce.jsx";
import anubha from "../../../../Dummy_data/ImgPages/Commerce/anubha_com.jpg"
import anubha_cv from "../../../../Dummy_data/ImgPages/Commerce/Anubha_com.pdf"
import male from "../../../../Dummy_data/images/male.png"
import female from "../../../../Dummy_data/images/female_user.png"
import deepika_cv from "../../../../Dummy_data/ImgPages/Commerce/Deepika_com.pdf"
import gunjan from "../../../../Dummy_data/ImgPages/Commerce/gunjan_com.png"
import gunjan_cv from "../../../../Dummy_data/ImgPages/Commerce/gunjan_com.pdf"
import gurup_cv from "../../../../Dummy_data/ImgPages/Commerce/Gurpinder_com.pdf"
import hritanshu from "../../../../Dummy_data/ImgPages/Commerce/Hritanshu_com.png"
import hritanshu_cv from "../../../../Dummy_data/ImgPages/Commerce/Hritanshu_com.pdf"
import indu_cv from "../../../../Dummy_data/ImgPages/Commerce/Indu_com.pdf"
import ishab from "../../../../Dummy_data/ImgPages/Commerce/isha_bhatt.png"
import ishab_cv from "../../../../Dummy_data/ImgPages/Commerce/isha_bhatt.pdf"
import ishag_cv from "../../../../Dummy_data/ImgPages/Commerce/Isha_Goel.pdf"
import kalpana from "../../../../Dummy_data/ImgPages/Commerce/kalpana_com.png"
import kalpana_cv from "../../../../Dummy_data/ImgPages/Commerce/kalpana_com.pdf"
import kavita from "../../../../Dummy_data/ImgPages/Commerce/Kavita_com.png"
import kavita_cv from "../../../../Dummy_data/ImgPages/Commerce/Kavita_com.pdf"
import madhu from "../../../../Dummy_data/ImgPages/Commerce/Madhu_com.png"
import madhu_cv from "../../../../Dummy_data/ImgPages/Commerce/Madhu_com.pdf"
import manisha from "../../../../Dummy_data/ImgPages/Commerce/Manisha_com.png"
import manisha_cv from "../../../../Dummy_data/ImgPages/Commerce/Manisha_com.pdf"
import mansi from "../../../../Dummy_data/ImgPages/Commerce/mansi_com.png"
import mansi_cv from "../../../../Dummy_data/ImgPages/Commerce/mansi_com.pdf"
import meeta_cv from "../../../../Dummy_data/ImgPages/Commerce/meeta_com.pdf"
import megha from "../../../../Dummy_data/ImgPages/Commerce/megha_com.png"
import megha_cv from "../../../../Dummy_data/ImgPages/Commerce/megha_com.pdf"
import minakshi from "../../../../Dummy_data/ImgPages/Commerce/Minakshi_com.png"
import minakshi_cv from "../../../../Dummy_data/ImgPages/Commerce/Minakshi_com.pdf"
import preeti from "../../../../Dummy_data/ImgPages/Commerce/Preeti_com.png"
import preeti_cv from "../../../../Dummy_data/ImgPages/Commerce/Preeti_com.pdf"
import raman from "../../../../Dummy_data/ImgPages/Commerce/Raman_com.png"
import raman_cv from "../../../../Dummy_data/ImgPages/Commerce/Raman_com.pdf"
import reema from "../../../../Dummy_data/ImgPages/Commerce/Reema_com.png"
import reema_cv from "../../../../Dummy_data/ImgPages/Commerce/Reema_com.pdf"
import renu from "../../../../Dummy_data/ImgPages/Commerce/renu_com.png"
import renu_cv from "../../../../Dummy_data/ImgPages/Commerce/Renu_com.pdf"
import richa from "../../../../Dummy_data/ImgPages/Commerce/Richa_com.png"
import richa_cv from "../../../../Dummy_data/ImgPages/Commerce/Richa_com.pdf"
import roopshikha from "../../../../Dummy_data/ImgPages/Commerce/Roopshikha_com.png"
import roopshikha_cv from "../../../../Dummy_data/ImgPages/Commerce/Roopshikha_com.pdf"
import sarita_cv from "../../../../Dummy_data/ImgPages/Commerce/Sarita_com.pdf"
import shuchita from "../../../../Dummy_data/ImgPages/Commerce/shuchita_com.png"
import shuchita_cv from "../../../../Dummy_data/ImgPages/Commerce/shuchita_com.pdf"
import soumya from "../../../../Dummy_data/ImgPages/Commerce/Soumya_com.jpg"
import soumya_cv from "../../../../Dummy_data/ImgPages/Commerce/Soumya_com.pdf"
import sunita from "../../../../Dummy_data/ImgPages/Commerce/Sunita_com.jpg"
import sunita_cv from "../../../../Dummy_data/ImgPages/Commerce/Sunita_com.pdf"
import sushma_cv from "../../../../Dummy_data/ImgPages/Commerce/Sushma_com.pdf"
import tonika from "../../../../Dummy_data/ImgPages/Commerce/tonika_com.png"
import tonika_cv from "../../../../Dummy_data/ImgPages/Commerce/tonika_com.pdf"
import tripti from "../../../../Dummy_data/ImgPages/Commerce/Tripti_com.jpg"
import tripti_cv from "../../../../Dummy_data/ImgPages/Commerce/Tripti_com.pdf"
function Com_faculty() {
  return (
    <div>Com_faculty</div>
  )
}

export default Com_faculty