export const Fac_info = [{
        id: 1,
        Fac_name: "Prof. Sarita Nanda ",
        Designation: "Vice Principal",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/Sarita_Nanda.jpg",
        cv: "/images/ImgPages/Biochemistry/Sarita_cv.pdf",
    },
    {
        id: 2,
        Fac_name: "Dr. Padamshree",
        Designation: "Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/padmshree.jpg",
        cv: "/images/ImgPages/Biochemistry/padam_cv.pdf",
    },

    {
        id: 3,
        Fac_name: "Dr. Anita Garg Mangla",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/anita_mangla.jpg",
        cv: "/images/ImgPages/Biochemistry/Anita_M.pdf",
    },
    {
        id: 4,
        Fac_name: "Dr. Neeru Dhamija",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/neeru.jpg",
        cv: "/images/ImgPages/Biochemistry/neeru_cv.pd",
    },
    {
        id: 5,
        Fac_name: "Dr. Leena Vij ",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/leena.jpg",
        cv: "/images/ImgPages/Biochemistry/Leena_cv.pdf",
    },
    {
        id: 6,
        Fac_name: "Dr. Radhika Gupta",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/Radhika.jpg",
        cv: "/images/ImgPages/Biochemistry/Radhika_cv.pdf",
    },
    {
        id: 7,
        Fac_name: "Dr. Anita Goel",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/anita_g.jpg",
        cv: "/images/ImgPages/Biochemistry/Anita_g_cv.pdf",
    },
    {
        id: 8,
        Fac_name: "Dr. Neeraj Dohare",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/neeraj.jpg",
        cv: "/images/ImgPages/Biochemistry/Neeraj_cv.pdf",
    },
    {
        id: 10,
        Fac_name: "Dr. K. Nirmala ",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/female_user.png",
        cv: "/images/ImgPages/Biochemistry/K_Nirmala_cv.pdf",
    },
    {
        id: 11,
        Fac_name: "Dr. Sunita Joshi",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/female_user.png",
        cv: "/images/ImgPages/Biochemistry/Sunita_joshi_cv.pdf",
    },
]

export const Bot_fac_info = [{
        id: 12,
        Fac_name: "Prof. Nidhi Gautam",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Nidhi_Gautam.jpg",
        cv: "/images/ImgPages/Botany/NidhiG_CV.pdf",
    },
    {
        id: 13,
        Fac_name: "Prof. Rama Pasricha",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Rama_Pasricha.jpg",
        cv: "/images/ImgPages/Botany/Rama_Pasricha_cv.pdf",
    },
    {
        id: 14,
        Fac_name: "Prof. Rekha Kathal",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Rekha_Kathal.jpg",
        cv: "/images/ImgPages/Botany/Rekha_Kathal_cv.pdf",
    },
    {
        id: 15,
        Fac_name: "Dr. Meenam Bhatia",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Meenam_Bhatia.jpg",
        cv: "/images/ImgPages/Botany/Meenam_Bhatia_cv.pdf",
    },

    {
        id: 16,
        Fac_name: "Dr. Sunita George",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/SUNITA_GEORGE.jpg",
        cv: "/images/ImgPages/Botany/Sunita_George.pdf",
    },

    {
        id: 17,
        Fac_name: "Dr. Meenakshi Sharma",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Meenakshi_Sharma.JPG",
        cv: "/images/ImgPages/Botany/Meenakshi_Sharma_cv.pdf",
    },
    {
        id: 18,
        Fac_name: "Dr. Vidhi Chaudhary",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Vidhi_Chaudhary.jpg",
        cv: "/images/ImgPages/Botany/Vidhi_Chaudhary_cv.pdf",
    },
    {
        id: 19,
        Fac_name: "Dr. Leleeka",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/leleeka_mayanglambam.jpg",
        cv: "/images/ImgPages/Botany/Mayanglambam_Leleeka_cv.pdf",
    },

    {
        id: 20,
        Fac_name: "Dr. Aradhana Yadav",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Aradhana_Yadav.jpg",
        cv: "/images/ImgPages/Botany/Aradhana_Yadav_cv.pdf",
    },
    {
        id: 21,
        Fac_name: "Dr. Pratibha Kumari",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Pratibha_Kumari.jpeg",
        cv: "/images/ImgPages/Botany/Pratibha_Kumari_cv.pdf",
    },
    {
        id: 22,
        Fac_name: "Dr. Shagun Danda",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Shagun_Danda.jpg",
        cv: "/images/ImgPages/Botany/Shagun_Danda_cv.pdf",
    },
    {
        id: 23,
        Fac_name: "Dr. Asmita Gupta",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Asmita_Gupta.jpg",
        cv: "/images/ImgPages/Botany/Asmita_Gupta_cv.pdf",
    },
    {
        id: 24,
        Fac_name: "Dr. Kamlesh Kumari",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Kamlesh_Kumari.jpg",
        cv: "/images/ImgPages/Botany/Kamlesh_Kumari.pdf",
    },

    {
        id: 25,
        Fac_name: "Dr. Sunita Sinha ",
        Designation: "Senior Reader",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Sunita_Sinha.png",
        cv: "/images/ImgPages/Botany/Sunita_Sinha_cv.pdf",
    },
    {
        id: 26,
        Fac_name: "Dr. Rajeshwari",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Rajeshwari_Madhavan.png",
        cv: "/images/ImgPages/Botany/Rajeshwari_Madhavan_cv.pdf",
    },
    {
        id: 27,
        Fac_name: "Dr. Neelam Pari",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Neelam_Malkani.png",
        cv: "/images/ImgPages/Botany/Neelam_Malkhani_cv.pdf",
    },
    {
        id: 28,
        Fac_name: "Dr. Sudha Prakash",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Sudha_Prakash.jpg",
        cv: "/images/ImgPages/Botany/Sudha_Prakash_cv.pdf",
    },
    {
        id: 29,
        Fac_name: "Dr. Subhashni Dewan",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Shubhasni_Dewan.jpg",
        cv: "#",
    },

    {
        id: 30,
        Fac_name: "Dr. Kanan Nanda",
        Designation: "Associate",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Kanan_Nanda.jpeg",
        cv: "#",
    },

]
export const Com_fac_info = [{
        id: 31,
        Fac_name: " Mrs. Meeta Mathur",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/female_user.png",
        cv: "/images/ImgPages/Commerce/meeta_com.pdf",
    },
    {
        id: 32,
        Fac_name: "Dr. Kalpana Vaish",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/kalpana_com.png",
        cv: "/images/ImgPages/Commerce/kalpana_com.pdf",
    },
    {
        id: 14,
        Fac_name: "Dr. Sunita",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Sunita_com.jpg",
        cv: "/images/ImgPages/Commerce/Sunita_com.pdf",
    },
    {
        id: 33,
        Fac_name: "Dr. Gurmeet Kaur",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Meenam_Bhatia.jpg",
        cv: "/images/ImgPages/Botany/Meenam_Bhatia_cv.pdf",
    },

    {
        id: 34,
        Fac_name: "Dr. Manisha Jaiswal",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Manisha_com.png",
        cv: "/images/ImgPages/Commerce/Manisha_com.pdf",
    },

    {
        id: 35,
        Fac_name: "Dr. Reema Popli Dehal",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Reema_com.png",
        cv: "/images/ImgPages/Commerce/Reema_com.pdf",
    },
    {
        id: 36,
        Fac_name: "Dr. Tonika Rana",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/tonika_com.png",
        cv: "/images/ImgPages/Commerce/tonika_com.pdf",
    },
    {
        id: 37,
        Fac_name: "Dr. Gunjan Gupta",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/gunjan_com.png",
        cv: "/images/ImgPages/Commerce/gunjan_com.pdf",
    },

    {
        id: 38,
        Fac_name: "Ms. Richa Kaur",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Richa_com.png",
        cv: "/images/ImgPages/Commerce/Richa_com.pdf",
    },
    {
        id: 39,
        Fac_name: "Ms. Mansi Kanojia",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/mansi_com",
        cv: "/images/ImgPages/Commerce/mansi_com.pdf",
    },
    {
        id: 40,
        Fac_name: "Dr. Isha Goel",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/female_user.png",
        cv: "/images/ImgPages/Commerce/Isha_Goel.pdf",
    },
    {
        id: 41,
        Fac_name: "Ms. Shuchita Verma",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/shuchita_com.png",
        cv: "/images/ImgPages/Commerce/shuchita_com.pdf",
    },
    {
        id: 42,
        Fac_name: "Ms. Deepika Jindal",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/female_user.png",
        cv: "/images/ImgPages/Commerce/Deepika_com.pdf",
    },

    {
        id: 43,
        Fac_name: "Ms. Raman Arora ",
        Designation: "Assistant Reader",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Raman_com.png",
        cv: "/images/ImgPages/Commerce/Raman_com.pdf",
    },
    {
        id: 44,
        Fac_name: "Dr. Meenakshi Paliwal",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Raman_com.png",
        cv: "/images/ImgPages/Commerce/Raman_com.pdf",
    },
    {
        id: 45,
        Fac_name: "Ms. Roopshikha",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Minakshi_com.png",
        cv: "/images/ImgPages/Commerce/Minakshi_com.pdf",
    },
    {
        id: 46,
        Fac_name: "Ms.Preeti Singh",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Preeti_com.png",
        cv: "/images/ImgPages/Commerce/Preeti_com.pdf",
    },
    {
        id: 47,
        Fac_name: "Ms. Isha Bhatt",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/isha_bhatt.png",
        cv: "/images/ImgPages/Commerce/isha_bhatt.pdf",
    },
    {
        id: 48,
        Fac_name: "Dr. Megha Jain",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/megha_com.png",
        cv: "/images/ImgPages/Commerce/megha_com.pdf",
    },
    {
        id: 49,
        Fac_name: "Ms. Hritanshu Jeph",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Hritanshu_com.png",
        cv: "/images/ImgPages/Commerce/Hritanshu_com.pdf",
    },
    {
        id: 50,
        Fac_name: "Ms. Soumya Sharma",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Soumya_com.jpg",
        cv: "/images/ImgPages/Commerce/Soumya_com.pdf",
    },
    {
        id: 51,
        Fac_name: "Dr. Renu Yadav",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/renu_com.png",
        cv: "/images/ImgPages/Commerce/Renu_com.pdf",
    },
    {
        id: 52,
        Fac_name: "Dr. Anubha Godara",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/anubha_com.jpg",
        cv: "/images/ImgPages/Commerce/Anubha_com.pdf",
    },
    {
        id: 53,
        Fac_name: "Ms. Tripti Goel",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Commerce/Tripti_com.jpg",
        cv: "/images/ImgPages/Commerce/Tripti_com.pdf",
    },

    {
        id: 54,
        Fac_name: "Dr. Madhu Agrawal",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/Commerce/Madhu_com.png",
        cv: "/images/ImgPages/Commerce/Madhu_com.pdf",
    },
    {
        id: 55,
        Fac_name: "Mrs. Sushma Arora",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/female_user.png",
        cv: "/images/ImgPages/Commerce/Sushma_com.pdf",
    },
    {
        id: 56,
        Fac_name: "Dr. Indu Jain",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/female_user.png",
        cv: "/images/ImgPages/Commerce/Indu_com.pdf",
    },
    {
        id: 57,
        Fac_name: "Mrs. Sarita Jain",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/female_user.png",
        cv: "/images/ImgPages/Commerce/Sarita_com.pdf",
    },
    {
        id: 58,
        Fac_name: "Prof. Kavita Sharma",
        Designation: "Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/Commerce/Kavita_com.png",
        cv: "/images/ImgPages/Commerce/Kavita_com.pdf",
    },
    {
        id: 59,
        Fac_name: "Prof. Shirin Rathore",
        Designation: "Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/male.png",
        cv: "#",
    },
    {
        id: 60,
        Fac_name: "Dr. Malti Gupta",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/female_user.png",
        cv: "#",
    },
    {
        id: 61,
        Fac_name: "Dr. Bimla Gautam",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/female_user.png",
        cv: "#",
    },

]

export const Bot_association_info = [{
        id: 62,
        Fac_name: "Mr. Suresh Kumar",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/2_Mr_Suresh_Kumar.jpg",
        Date_of_joining: "Date of Joining- 21/12/1988",

    },
    {
        id: 63,
        Fac_name: "MR. Ramesh Nagar",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/1_Mr_Ramesh_Nagar.JPG",
        Date_of_joining: "Date of Joining- 29/03/1993",

    },
    {
        id: 64,
        Fac_name: "Mr. Satish Kumar Chauhan",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/3_Mr_Satish_Kumar_Chauhan.jpg",
        Date_of_joining: "Date of Joining- 12/06/2006",

    },
    {
        id: 65,
        Fac_name: "Mr. Mahendra Pal",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/4_Mr_Mahendra_Pal.JPG",
        Date_of_joining: "Date of Joining- 12/06/2006",

    },
    {
        id: 66,
        Fac_name: "Mr. Rambir Mann",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/5_Mr_Rambir_Mann.jpg",
        Date_of_joining: "Date of Joining- 18/06/2009",

    },
    {
        id: 67,
        Fac_name: "Mr. Niraj",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/6_Mr_Neeraj.jpg",
        Date_of_joining: "Date of Joining- 12/09/2019",

    },
    {
        id: 68,
        Fac_name: "Ms. Gitanjali",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/7_Ms_Geetanjali.jpg",
        Date_of_joining: "Date of Joining- 12/09/2019",

    },




]
export const Chem_fac_info = [{
        id: 69,
        Fac_name: "Dr. Shuchi Sharma",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/Suchi.jpg",
        cv: "/images/ImgPages/Chemistry/Shuchi.pdf",
    },
    {
        id: 70,
        Fac_name: "Dr. Archana Gupta",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/Archana.jpg",
        cv: "/images/ImgPages/Chemistry/ARCHANA.pdf",
    },

    {
        id: 71,
        Fac_name: "Prof. Priti Malhotra",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/preeti_m.jpg",
        cv: "/images/ImgPages/Chemistry/Priti_m.pdf",
    },
    {
        id: 72,
        Fac_name: "Dr. Asha",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/female_user.png",
        cv: "#",
    },
    {
        id: 73,
        Fac_name: "Dr. Darshan Singh",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/Darshan.jpg",
        cv: "/images/ImgPages/Chemistry/DARSHAN.pdf",
    },
    {
        id: 74,
        Fac_name: "Dr. Ritu Gupta",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/Ritu.jpg",
        cv: "/images/ImgPages/Chemistry/Ritu.pdf",
    },
    {
        id: 75,
        Fac_name: "Dr. Avneet Kaur",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/Avneet.jpg",
        cv: "/images/ImgPages/Chemistry/Avneet.pdf",
    },
    {
        id: 76,
        Fac_name: "Dr. Arti Jain",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/Arti.jpg",
        cv: "/images/ImgPages/Chemistry/ARTI.pdf",
    },
    {
        id: 77,
        Fac_name: "Dr. Aditi Puri",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/Aditi.jpg",
        cv: "/images/ImgPages/Chemistry/Aditi.pdf",
    },
    {
        id: 78,
        Fac_name: "Dr. Anamika Debnath",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/Anamika.png",
        cv: "/images/ImgPages/Chemistry/Anamika.pdf",
    },
    {
        id: 79,
        Fac_name: "Dr. Anuradha",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/anuradha.jpeg",
        cv: "/images/ImgPages/Chemistry/Anuradha.pdf",
    },
    {
        id: 80,
        Fac_name: "Dr. Preeti Chadha",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/preeti.jpg",
        cv: "/images/ImgPages/Chemistry/preeti.pdf",
    },
    {
        id: 81,
        Fac_name: "Dr. Divya Mathur",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/Divya.jpg",
        cv: "/images/ImgPages/Chemistry/Divya.pdf",
    },
    {
        id: 82,
        Fac_name: "Dr. Gauri Ahuja",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Chemistry/Gauri.jpg",
        cv: "/images/ImgPages/Chemistry/GAURI.pdf",
    },
    {
        id: 83,
        Fac_name: "Dr. Arif Ahamad",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/male.png",
        cv: "#",
    },
]





export const Eco_fac_info = [{
        id: 84,
        Fac_name: "Dr. Malini Sharma",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Malini.jpg",
        cv: "/images/ImgPages/Economics/Malini_cv.pdf",
    },
    {
        id: 85,
        Fac_name: "Ms. Pooja Khanna",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Pooja_k.jpg",
        cv: "/images/ImgPages/Economics/Pooja_k_cv.pdf",
    },
    {
        id: 86,
        Fac_name: "Ms. Ritu Khanna",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Ritu.jpg",
        cv: "#",
    },
    {
        id: 87,
        Fac_name: "Dr. Rita Rani",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Rita.png",
        cv: "/images/ImgPages/Economics/Rita_cv.pdf",
    },
    {
        id: 88,
        Fac_name: "Ms. Pooja Sharma",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Pooja_s.jpg",
        cv: "/images/ImgPages/Economics/Pooja_s_cv.pdf",
    },
    {
        id: 89,
        Fac_name: "Ms. Shikha Singh",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Sikha.png",
        cv: "/images/ImgPages/Economics/Shikha_cv.pdf",
    },
    {
        id: 90,
        Fac_name: "Ms. Sumeet Goyal",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Sumeet.png",
        cv: "/images/ImgPages/Economics/Sumeet_cv.pdf",
    },
    {
        id: 91,
        Fac_name: "Ms. Priyanka Yadav",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Priyanka.png",
        cv: "/images/ImgPages/Economics/Priyanka_cv.pdf",
    },
    {
        id: 92,
        Fac_name: "Ms. Saachi Bhutani",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Pooja_k.jpg",
        cv: "/images/ImgPages/Economics/Pooja_k_cv.pdf",
    },
    {
        id: 93,
        Fac_name: "Ms. Aisha Ahmed",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Saachi.png",
        cv: "/images/ImgPages/Economics/Saachi_cv.pdf",
    },
    {
        id: 94,
        Fac_name: "Mr. Nitish Kashyap",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Nitish.png",
        cv: "/images/ImgPages/Economics/Nitish_cv.pdf",
    },
    {
        id: 95,
        Fac_name: "Mr. Ashok Kumar",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Economics/Ashok.png",
        cv: "/images/ImgPages/Economics/Ashok_cv.pdf",
    },

]



export const Eng_fac_info = [{
        id: 96,
        Fac_name: "Mrs. Sangeeta Gupta",
        Designation: "Senior Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Sangeeta_eng.jpg",
        cv: "/images/ImgPages/English/Sangeeta_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Dr. Deepshikha Mahanta Bortamuly",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Deepshikha_eng.png",
        cv: "/images/ImgPages/English/Deepshikha_eng_cv.pdf",
    },

    {
        id: 98,
        Fac_name: "Ms. Haritha P.",
        Designation: "Assitant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Haritha_eng.png",
        cv: "/images/ImgPages/English/Haritha_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Dr. Prastavana Mohan",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Prastavana_eng.jpg",
        cv: "/images/ImgPages/English/Prastavana_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Dr. Sakshi Wason",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Sakshi_eng.png",
        cv: "/images/ImgPages/English/Sakshi_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Ms. Saneya",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Saneya_eng.png",
        cv: "/images/ImgPages/English/Saneya_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Ms. Vandana",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Vandana_eng.jpg",
        cv: "/images/ImgPages/English/Vandana_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Ms. Violina Borah",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Violina_eng.jpg",
        cv: "/images/ImgPages/English/Violina_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Ms. Trisha Mitra",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Trisha_eng.jpg",
        cv: "/images/ImgPages/English/Trisha_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Mr. Owais Farooq",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Owais_eng.png",
        cv: "/images/ImgPages/English/Owais_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Ms. Kiran Yadav",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Kiran_eng.png",
        cv: "/images/ImgPages/English/Kiran_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Ms. Richa Dawar",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Richa_eng.jpg",
        cv: "/images/ImgPages/English/Richa_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Ms. Rashmi Yadav",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Rashmi_eng.jpg",
        cv: "/images/ImgPages/English/Rashmi_eng_cv.pdf",
    },
    {
        id: 97,
        Fac_name: "Mr. Kehru L",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/English/Kaihru_eng.jpg",
        cv: "/images/ImgPages/English/Kaihru_eng_cv.pdf",
    },






]