export const Fac_info = [{
        id: 1,
        Fac_name: "Prof. Sarita Nanda ",
        Designation: "Vice Principal",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/Sarita_Nanda.jpg",
        cv: "/images/ImgPages/Biochemistry/Sarita_cv.pdf",
    },
    {
        id: 2,
        Fac_name: "Dr. Padamshree",
        Designation: "Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/padmshree.jpg",
        cv: "/images/ImgPages/Biochemistry/padam_cv.pdf",
    },

    {
        id: 3,
        Fac_name: "Dr. Anita Garg Mangla",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/anita_mangla.jpg",
        cv: "/images/ImgPages/Biochemistry/Anita_M.pdf",
    },
    {
        id: 4,
        Fac_name: "Dr. Neeru Dhamija",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/neeru.jpg",
        cv: "/images/ImgPages/Biochemistry/neeru_cv.pd",
    },
    {
        id: 5,
        Fac_name: "Dr. Leena Vij ",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/leena.jpg",
        cv: "/images/ImgPages/Biochemistry/Leena_cv.pdf",
    },
    {
        id: 6,
        Fac_name: "Dr. Radhika Gupta",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/Radhika.jpg",
        cv: "/images/ImgPages/Biochemistry/Radhika_cv.pdf",
    },
    {
        id: 7,
        Fac_name: "Dr. Anita Goel",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/anita_g.jpg",
        cv: "/images/ImgPages/Biochemistry/Anita_g_cv.pdf",
    },
    {
        id: 8,
        Fac_name: "Dr. Neeraj Dohare",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Biochemistry/neeraj.jpg",
        cv: "/images/ImgPages/Biochemistry/Neeraj_cv.pdf",
    },
    {
        id: 10,
        Fac_name: "Dr. K. Nirmala ",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/female_user.png",
        cv: "/images/ImgPages/Biochemistry/K_Nirmala_cv.pdf",
    },
    {
        id: 11,
        Fac_name: "Dr. Sunita Joshi",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/female_user.png",
        cv: "/images/ImgPages/Biochemistry/Sunita_joshi_cv.pdf",
    },
]
export const Bot_fac_info = [{
        id: 12,
        Fac_name: "Prof. Nidhi Gautam",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Nidhi_Gautam.jpg",
        cv: "/images/ImgPages/Botany/NidhiG_CV.pdf",
    },

    {
        id: 13,
        Fac_name: "Prof. Rama Pasricha",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Rama_Pasricha.jpg",
        cv: "/images/ImgPages/Botany/Rama_Pasricha_cv.pdf",
    },
    {
        id: 14,
        Fac_name: "Prof. Rekha Kathal",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Rekha_Kathal.jpg",
        cv: "/images/ImgPages/Botany/Rekha_Kathal_cv.pdf",
    },
    {
        id: 15,
        Fac_name: "Dr. Meenam Bhatia",
        Designation: "Associate Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Meenam_Bhatia.jpg",
        cv: "/images/ImgPages/Botany/Meenam_Bhatia_cv.pdf",
    },

    {
        id: 16,
        Fac_name: "Dr. Sunita George",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/SUNITA_GEORGE.jpg",
        cv: "/images/ImgPages/Botany/Sunita_George.pdf",
    },

    {
        id: 17,
        Fac_name: "Dr. Meenakshi Sharma",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Meenakshi_Sharma.JPG",
        cv: "/images/ImgPages/Botany/Meenakshi_Sharma_cv.pdf",
    },
    {
        id: 18,
        Fac_name: "Dr. Vidhi Chaudhary",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Vidhi_Chaudhary.jpg",
        cv: "/images/ImgPages/Botany/Vidhi_Chaudhary_cv.pdf",
    },
    {
        id: 19,
        Fac_name: "Dr. Leleeka",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/leleeka_mayanglambam.jpg",
        cv: "/images/ImgPages/Botany/Mayanglambam_Leleeka_cv.pdf",
    },

    {
        id: 20,
        Fac_name: "Dr. Aradhana Yadav",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Aradhana_Yadav.jpg",
        cv: "/images/ImgPages/Botany/Aradhana_Yadav_cv.pdf",
    },
    {
        id: 21,
        Fac_name: "Dr. Pratibha Kumari",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Pratibha_Kumari.jpeg",
        cv: "/images/ImgPages/Botany/Pratibha_Kumari_cv.pdf",
    },
    {
        id: 22,
        Fac_name: "Dr. Shagun Danda",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Shagun_Danda.jpg",
        cv: "/images/ImgPages/Botany/Shagun_Danda_cv.pdf",
    },
    {
        id: 23,
        Fac_name: "Dr. Asmita Gupta",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Asmita_Gupta.jpg",
        cv: "/images/ImgPages/Botany/Asmita_Gupta_cv.pdf",
    },
    {
        id: 24,
        Fac_name: "Dr. Kamlesh Kumari",
        Designation: "Assistant Professor",
        filter: "Current",
        img: "/images/ImgPages/Botany/Kamlesh_Kumari.jpg",
        cv: "/images/ImgPages/Botany/Kamlesh_Kumari.pdf",
    },

    {
        id: 25,
        Fac_name: "Dr. Sunita Sinha ",
        Designation: "Senior Reader",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Sunita_Sinha.png",
        cv: "/images/ImgPages/Botany/Sunita_Sinha_cv.pdf",
    },
    {
        id: 26,
        Fac_name: "Dr. Rajeshwari",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Rajeshwari_Madhavan.png",
        cv: "/images/ImgPages/Botany/Rajeshwari_Madhavan_cv.pdf",
    },
    {
        id: 27,
        Fac_name: "Dr. Neelam Pari",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Neelam_Malkani.png",
        cv: "/images/ImgPages/Botany/Neelam_Malkhani_cv.pdf",
    },
    {
        id: 28,
        Fac_name: "Dr. Sudha Prakash",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Sudha_Prakash.jpg",
        cv: "/images/ImgPages/Botany/Sudha_Prakash_cv.pdf",
    },
    {
        id: 29,
        Fac_name: "Dr. Subhashni Dewan",
        Designation: "Associate Professor",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Shubhasni_Dewan.jpg",
        cv: "#",
    },

    {
        id: 30,
        Fac_name: "Dr. Kanan Nanda",
        Designation: "Principal (2007-10)",
        filter: "Superannuated",
        img: "/images/ImgPages/Botany/Kanan_Nanda.jpeg",
        cv: "#",
    },

]
export const Bot_association_info = [{
        id: 31,
        Fac_name: "Mr. Suresh Kumar",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/2_Mr_Suresh_Kumar.jpg",
        Date_of_joining: "Date of Joining- 21/12/1988",

    },
    {
        id: 32,
        Fac_name: "MR. Ramesh Nagar",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/1_Mr_Ramesh_Nagar.JPG",
        Date_of_joining: "Date of Joining- 29/03/1993",

    },
    {
        id: 33,
        Fac_name: "Mr. Satish Kumar Chauhan",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/3_Mr_Satish_Kumar_Chauhan.jpg",
        Date_of_joining: "Date of Joining- 12/06/2006",

    },
    {
        id: 34,
        Fac_name: "Mr. Mahendra Pal",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/4_Mr_Mahendra_Pal.JPG",
        Date_of_joining: "Date of Joining- 12/06/2006",

    },
    {
        id: 35,
        Fac_name: "Mr. Rambir Mann",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/5_Mr_Rambir_Mann.jpg",
        Date_of_joining: "Date of Joining- 18/06/2009",

    },
    {
        id: 36,
        Fac_name: "Mr. Niraj",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/6_Mr_Neeraj.jpg",
        Date_of_joining: "Date of Joining- 12/09/2019",

    },
    {
        id: 37,
        Fac_name: "Ms. Gitanjali",
        Designation: "Laboratory Asistant",
        filter: "Current",
        img: "/images/ImgPages/Botany/7_Ms_Geetanjali.jpg",
        Date_of_joining: "Date of Joining- 12/09/2019",

    },




]